# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ad81450409672012b12c210f4eaefdd2bc26df795a25eee4e196a987334fd2a709d9fe9fdbb61856d02500958fdc32aefc3439c0e93c73131a340b7f7d47d80

test:
  secret_key_base: fc9da30ae67a42e103249ae0bc1f3372cdfb5ea5c2eced77de0b2f8af8105ad6f202a9426d9ece87ed7266a88b030a48735fe281ff39d8bcc31b79373b7cf2e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
